### ISSUE TITLE
Heuristics scan incredibly minor issue

### ISSUE THREAD

**Issue by rjzak** [horsicq/XMachOViewer#1]
I'm sure this is well beyond the purpose & scope of your application, but figured I'd share. Using XMachOViewer with a M68k Mach-O file from NeXTSTEP results in the heuristics scan item saying "Unknown". Everything else works as it should. Binary available at http://gamers.org/pub/idgames/idstuff/doom/nextstep/NeXTdoom1_2.tar.gz.

**Comment by horsicq** [comment]
I did not see any M86k Mach-O files before. Thanks a lot for the Bugreport!

**Comment by horsicq** [comment]
Fixed:
https://github.com/horsicq/XMachOViewer/commit/1b56993863b3ee16a2510d55e2ea0f551ce42542
https://github.com/horsicq/XMachOViewer/commit/0471ffcb32b501933bbb294eacddb57e11ec86b5

Download beta version with m68k support: https://github.com/horsicq/XMachOViewer/releases/tag/0.02b1
