### ISSUE TITLE
New arm64e code 80000002 cannot be detected

### ISSUE THREAD

**Issue by heyuhengmatt** [horsicq/XMachOViewer#3]
![image](https://user-images.githubusercontent.com/36391318/143970055-f0432e2a-d464-4a65-a2bb-3b17bb84303d.png)
this arch is in fact arm64e due to apple's changing in arch code.

**Comment by horsicq** [comment]
Thanks a lot for the report!

**Comment by horsicq** [comment]
Fixed. I will make release version in a week.
